version: '3.8'

volumes:
  freeport_cache:
  freeport_data_volume:
  freeport_bch_wallet_data:
  freeport_xmr_wallet_data:
  freeport_btc_wallet_data:

networks:
  freeport:
    external: true

name: Freeport
services:

  backend:
    image: anekdotin/freeport-backend:latest
    restart: always
    volumes:
        - /mnt/md1/freeport/data:/data
    depends_on:
        - redis
    deploy:
      replicas: 4
    env_file:
        - .env
    networks:
      - freeport

  backendproxy:
      container_name: freeport-backend-proxy
      image: nginx:latest
      restart: always
      volumes:
        - /home/droid/docker/freeport/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "5000:5000"
      depends_on:
        - backend
      networks:
        - freeport

  frontend:
    image: anekdotin/freeport-frontend:latest
    restart: on-failure
    ports:
      - "5010:5010"
    networks:
      - freeport


  redis:
      image: redis:latest
      restart: on-failure
      ports:
        - '6379:6379'
      volumes:
        - /mnt/md1/freeport/redis:/data
      env_file:
        - .env
      networks:
        - freeport


  coinprice:
    image: anekdotin/freeport-coinprices:latest
    ports:
        - '5054:5054'
    networks:
      - freeport

  crons:
    image: anekdotin/freeport-crons:latest
    ports:
        - '5055:5055'
    volumes:
        - /mnt/md1/freeport/data:/data
    env_file:
        - .env
    networks:
      - freeport


  wallet_btc:
    image: anekdotin/freeport-wallet-btc:latest
    ports:
        - '5075:5075'
    networks:
      - freeport
    env_file:
        - .env
    volumes:
        - /mnt/md1/freeport/data:/btc_wallet


  wallet_bch:
    image: anekdotin/freeport-wallet-bch:latest
    ports:
        - '5080:5080'
    networks:
      - freeport
    env_file:
        - .env
    volumes:
        - /mnt/md1/freeport/data:/bch_wallet


  wallet_xmr:
    image: anekdotin/freeport-wallet-xmr:latest
    ports:
        - '5085:5085'
    env_file:
        - .env
    volumes:
        - /mnt/md1/freeport/data:/xmr_wallet
    networks:
      - freeport


  controller:
    image: anekdotin/freeport-controller:latest
    ports:
        - '5099:5099'
    networks:
      - freeport