version: '3.8'

volumes:
  freeport_cache:
  freeport_data_volume:
  freeport_frontend_volume:
  freeport_api_volume:

networks:
  freeport:
    external: true

services:

  api:
    container_name: freeport-api
    restart: always
    build:
        context: ../api
        dockerfile: Dockerfile.api-prod
    volumes:
        - freeport_api_volume:/home/droid/freeport/data
        - freeport_data_volume:/home/droid/freeport/data
    depends_on:
        -   redis
    ports:
      - '5000:5000'
    networks:
      - freeport

  frontend:
    container_name: freeport-frontend
    restart: on-failure
    build:
      context: ../frontend
      dockerfile: Dockerfile.frontend-prod
    volumes:
      - freeport_frontend_volume:/app
    ports:
      - '5173:5173'
    networks:
      - freeport
    command: npm run serve

  redis:
      container_name: freeport-redis
      image: redis:latest
      restart: on-failure
      ports:
        - '6379:6379'
      volumes:
        - freeport_cache:/data
      networks:
        - freeport

