version: '3.8'

volumes:
  freeport_cache:
  freeport_data_volume:
  db:
    driver: local

networks:
  freeport:
    external: true

services:
  frontend:
    container_name: freeport-frontend
    image: freeport/freeport-frontend
    restart: on-failure
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend:/app
    ports:
      - '5173:5173'
    networks:
      - freeport
    command: npm run serve


  api:
    container_name: freeport-api
    image: freeport/freeport-api
    restart: on-failure
    build:
        context: ../backend
        dockerfile: Dockerfile
    volumes:
        - ../backend:/app
        - freeport_data_volume:/home/droid/freeport/data
    depends_on:
        -   redis
    ports:
      - '5000:5000'
    networks:
      - freeport

  database:
    image: postgres:latest
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ../dbdata/db:/var/lib/postgresql/data
      - ../dbdata/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - freeport


  redis:
      container_name: freeport-redis
      image: redis:latest
      command: redis-server --save 20 1 --loglevel warning
      restart: on-failure
      ports:
        - '6379:6379'
      volumes:
        - freeport_cache:/home/droid/freeport/data/redis
      networks:
        - freeport


  coinprice:
    container_name: freeport-coinprices
    image: freeport/freeport-coinprices
    ports:
        - '5054:5054'
    volumes:
        - ../coinprices:/app
    build:
       context: ../coinprices
       dockerfile: Dockerfile
    networks:
      - freeport


  crons:
    container_name: freeport-crons
    image: freeport/freeport-crons
    ports:
        - '5055:5055'
    volumes:
        - ../crons:/app
    build:
       context: ../crons
       dockerfile: Dockerfile
    networks:
      - freeport



  wallet_btc:
    container_name: freeport-wallet_btc
    image: freeport/freeport-wallet_btc
    ports:
        - '5075:5075'
    volumes:
        - ../wallet_btc:/app
    build:
       context: ../wallet_btc
       dockerfile: Dockerfile
    networks:
      - freeport


  wallet_bch:
    container_name: freeport-wallet_bch
    image: freeport/freeport-wallet_bch
    ports:
        - '5080:5080'
    volumes:
        - ../wallet_bch:/app
    build:
       context: ../wallet_bch
       dockerfile: Dockerfile
    networks:
      - freeport


  wallet_xmr:
    container_name: freeport-wallet_xmr
    image: freeport/freeport-wallet_xmr
    ports:
        - '5085:5085'
    volumes:
        - ../wallet_xmr:/app
    build:
       context: ../wallet_xmr
       dockerfile: Dockerfile
    networks:
      - freeport
