version: '3.8'

volumes:
  freeport_cache:
  freeport_data_volume:

networks:
  freeport:
    external: true

services:

  backend:
    container_name: freeport-backend
    restart: always
    build:
        context: ../backend
        dockerfile: Dockerfile.prod
    volumes:
        - freeport_data_volume:/home/droid/freeport/data
    depends_on:
        -   redis
    ports:
      - '5000:5000'
    networks:
      - freeport

  frontend:
    container_name: freeport-frontend
    restart: on-failure
    build:
      context: ../frontend
      dockerfile: Dockerfile.prod
    ports:
      - '5173:5173'
    networks:
      - freeport
    command: npm run build

  redis:
      image: redis:latest
      restart: on-failure
      ports:
        - '6379:6379'
      volumes:
        - freeport_cache:/data
      networks:
        - freeport


  coinprice:
    container_name: freeport-coinprices
    ports:
        - '5054:5054'
    build:
       context: ../coinprices
       dockerfile: Dockerfile.prod
    networks:
      - freeport


  crons:
    container_name: freeport-crons
    ports:
        - '5055:5055'
    build:
       context: ../crons
       dockerfile: Dockerfile.prod
    networks:
      - freeport



  wallet_btc:
    container_name: freeport-wallet-btc
    ports:
        - '5075:5075'
    build:
       context: ../wallet_btc
       dockerfile: Dockerfile.prod
    networks:
      - freeport


  wallet_bch:
    container_name: freeport-wallet-bch
    ports:
        - '5080:5080'
    build:
       context: ../wallet_bch
       dockerfile: Dockerfile.prod
    networks:
      - freeport


  wallet_xmr:
    container_name: freeport-wallet-xmr
    ports:
        - '5085:5085'
    build:
       context: ../wallet_xmr
       dockerfile: Dockerfile.prod
    networks:
      - freeport
